#!/bin/sh
while read file
do
    case "$1" in
        "C-d")
            mv "$file" ~/.trash ;;
        "C-r")
            convert -rotate 90 "$file" "$file" ;;
        "C-c")
            xclip -selection clipboard "$file" -t image/png
                ;;
        "C-w")
            nitrogen --save --set-zoom-fill "$file" ;;
    esac
done
